export const path = {
  home: "/",
  product: "/product",
  cart: "/cart",
  signUp: "/sign-up",
  signIn: "/sign-in",
  purchase: "user/purchase",
  profile: "/user/profile",
  order: "/user/order",
  user: "/user",
  userUpdate: "/dashboard/user/update",
  userAddNew: "/dashboard/user/add",
  userManage: "/dashboard/user/manage",
  password: "/user/password",
  search: "/search",
  dashboard: "/dashboard",
  banner: "/dashboard/banner",
  address: "/dashboard/shop/address",
  productManage: "/dashboard/product",
  productAddNew: "/dashboard/product/add-new",
  productUpdate: "/dashboard/product/update",
  orderManage: "/dashboard/order",
  orderUpdate: "/dashboard/order/update",
};
